import React from 'react';
import {string} from 'prop-types';
import classNames from '@thomann/classnames';
import style from './Icon.module.css';

/**
 *
 * @param className
 * @param type
 * @param size
 * @returns {*}
 * @constructor
 */
const Icon = ({className = null, type, size = null}) => {
    const href = `#entypo-${type}`;

    className = classNames(style.icon, {
        [style[size]]: (size),
    }, className);

    return (
        <i className={className}>
            <svg
                className={style.vector}
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
            >
                <use xlinkHref={href}/>
            </svg>
        </i>
    );
};

Icon.propTypes = {
    type: string.isRequired,
};

Icon.Type = {
    ADD_TO_LIST: 'add-to-list',
    ADD_USER: 'add-user',
    ADDRESS: 'address',
    ADJUST: 'adjust',
    AIR: 'air',
    AIRCRAFT_LANDING: 'aircraft-landing',
    AIRCRAFT_TAKE_OFF: 'aircraft-take-off',
    AIRCRAFT: 'aircraft',
    ALIGN_BOTTOM: 'align-bottom',
    ALIGN_HORIZONTAL_MIDDLE: 'align-horizontal-middle',
    ALIGN_LEFT: 'align-left',
    ALIGN_RIGHT: 'align-right',
    ALIGN_TOP: 'align-top',
    ALIGN_VERTICAL_MIDDLE: 'align-vertical-middle',
    ARCHIVE: 'archive',
    AREA_GRAPH: 'area-graph',
    ARROW_BOLD_DOWN: 'arrow-bold-down',
    ARROW_BOLD_LEFT: 'arrow-bold-left',
    ARROW_BOLD_RIGHT: 'arrow-bold-right',
    ARROW_BOLD_UP: 'arrow-bold-up',
    ARROW_DOWN: 'arrow-down',
    ARROW_LEFT: 'arrow-left',
    ARROW_LONG_DOWN: 'arrow-long-down',
    ARROW_LONG_LEFT: 'arrow-long-left',
    ARROW_LONG_RIGHT: 'arrow-long-right',
    ARROW_LONG_UP: 'arrow-long-up',
    ARROW_RIGHT: 'arrow-right',
    ARROW_UP: 'arrow-up',
    ARROW_WITH_CIRCLE_DOWN: 'arrow-with-circle-down',
    ARROW_WITH_CIRCLE_LEFT: 'arrow-with-circle-left',
    ARROW_WITH_CIRCLE_RIGHT: 'arrow-with-circle-right',
    ARROW_WITH_CIRCLE_UP: 'arrow-with-circle-up',
    ATTACHMENT: 'attachment',
    AWARENESS_RIBBON: 'awareness-ribbon',
    BACK_IN_TIME: 'back-in-time',
    BACK: 'back',
    BAR_GRAPH: 'bar-graph',
    BATTERY: 'battery',
    BEAMED_NOTE: 'beamed-note',
    BELL: 'bell',
    BLACKBOARD: 'blackboard',
    BLOCK: 'block',
    BOOK: 'book',
    BOOKMARK: 'bookmark',
    BOOKMARKS: 'bookmarks',
    BOWL: 'bowl',
    BOX: 'box',
    BRIEFCASE: 'briefcase',
    BROWSER: 'browser',
    BRUSH: 'brush',
    BUCKET: 'bucket',
    BUG: 'bug',
    CAKE: 'cake',
    CALCULATOR: 'calculator',
    CALENDAR: 'calendar',
    CAMERA: 'camera',
    CCW: 'ccw',
    CHAT: 'chat',
    CHECK: 'check',
    CHEVRON_DOWN: 'chevron-down',
    CHEVRON_LEFT: 'chevron-left',
    CHEVRON_RIGHT: 'chevron-right',
    CHEVRON_SMALL_DOWN: 'chevron-small-down',
    CHEVRON_SMALL_LEFT: 'chevron-small-left',
    CHEVRON_SMALL_RIGHT: 'chevron-small-right',
    CHEVRON_SMALL_UP: 'chevron-small-up',
    CHEVRON_THIN_DOWN: 'chevron-thin-down',
    CHEVRON_THIN_LEFT: 'chevron-thin-left',
    CHEVRON_THIN_RIGHT: 'chevron-thin-right',
    CHEVRON_THIN_UP: 'chevron-thin-up',
    CHEVRON_UP: 'chevron-up',
    CHEVRON_WITH_CIRCLE_DOWN: 'chevron-with-circle-down',
    CHEVRON_WITH_CIRCLE_LEFT: 'chevron-with-circle-left',
    CHEVRON_WITH_CIRCLE_RIGHT: 'chevron-with-circle-right',
    CHEVRON_WITH_CIRCLE_UP: 'chevron-with-circle-up',
    CIRCLE_WITH_CROSS: 'circle-with-cross',
    CIRCLE_WITH_MINUS: 'circle-with-minus',
    CIRCLE_WITH_PLUS: 'circle-with-plus',
    CIRCLE: 'circle',
    CIRCULAR_GRAPH: 'circular-graph',
    CLAPPERBOARD: 'clapperboard',
    CLASSIC_COMPUTER: 'classic-computer',
    CLIPBOARD: 'clipboard',
    CLOCK: 'clock',
    CLOUD: 'cloud',
    CODE: 'code',
    COG: 'cog',
    COLOURS: 'colours',
    COMPASS: 'compass',
    CONTROLLER_FAST_BACKWARD: 'controller-fast-backward',
    CONTROLLER_FAST_FORWARD: 'controller-fast-forward',
    CONTROLLER_JUMP_TO_START: 'controller-jump-to-start',
    CONTROLLER_NEXT: 'controller-next',
    CONTROLLER_PAUS: 'controller-paus',
    CONTROLLER_PLAY: 'controller-play',
    CONTROLLER_RECORD: 'controller-record',
    CONTROLLER_STOP: 'controller-stop',
    CONTROLLER_VOLUME: 'controller-volume',
    COPY: 'copy',
    CREATIVE_COMMONS_ATTRIBUTION: 'creative-commons-attribution',
    CREATIVE_COMMONS_NODERIVS: 'creative-commons-noderivs',
    CREATIVE_COMMONS_NONCOMMERCIAL_EU: 'creative-commons-noncommercial-eu',
    CREATIVE_COMMONS_NONCOMMERCIAL_US: 'creative-commons-noncommercial-us',
    CREATIVE_COMMONS_PUBLIC_DOMAIN: 'creative-commons-public-domain',
    CREATIVE_COMMONS_REMIX: 'creative-commons-remix',
    CREATIVE_COMMONS_SHARE: 'creative-commons-share',
    CREATIVE_COMMONS_SHAREALIKE: 'creative-commons-sharealike',
    CREATIVE_COMMONS: 'creative-commons',
    CREDIT_CARD: 'credit-card',
    CREDIT: 'credit',
    CROP: 'crop',
    CROSS: 'cross',
    CUP: 'cup',
    CW: 'cw',
    CYCLE: 'cycle',
    DATABASE: 'database',
    DIAL_PAD: 'dial-pad',
    DIRECTION: 'direction',
    DOCUMENT_LANDSCAPE: 'document-landscape',
    DOCUMENT: 'document',
    DOCUMENTS: 'documents',
    DOT_SINGLE: 'dot-single',
    DOTS_THREE_HORIZONTAL: 'dots-three-horizontal',
    DOTS_THREE_VERTICAL: 'dots-three-vertical',
    DOTS_TWO_HORIZONTAL: 'dots-two-horizontal',
    DOTS_TWO_VERTICAL: 'dots-two-vertical',
    DOWNLOAD: 'download',
    DRINK: 'drink',
    DRIVE: 'drive',
    DROP: 'drop',
    EDIT: 'edit',
    EMAIL: 'email',
    EMOJI_FLIRT: 'emoji-flirt',
    EMOJI_HAPPY: 'emoji-happy',
    EMOJI_NEUTRAL: 'emoji-neutral',
    EMOJI_SAD: 'emoji-sad',
    ERASE: 'erase',
    ERASER: 'eraser',
    EXPORT: 'export',
    EYE_WITH_LINE: 'eye-with-line',
    EYE: 'eye',
    FEATHER: 'feather',
    FINGERPRINT: 'fingerprint',
    FLAG: 'flag',
    FLASH: 'flash',
    FLASHLIGHT: 'flashlight',
    FLAT_BRUSH: 'flat-brush',
    FLOW_BRANCH: 'flow-branch',
    FLOW_CASCADE: 'flow-cascade',
    FLOW_LINE: 'flow-line',
    FLOW_PARALLEL: 'flow-parallel',
    FLOW_TREE: 'flow-tree',
    FLOWER: 'flower',
    FOLDER_IMAGES: 'folder-images',
    FOLDER_MUSIC: 'folder-music',
    FOLDER_VIDEO: 'folder-video',
    FOLDER: 'folder',
    FORWARD: 'forward',
    FUNNEL: 'funnel',
    GAME_CONTROLLER: 'game-controller',
    GAUGE: 'gauge',
    GLOBE: 'globe',
    GRADUATION_CAP: 'graduation-cap',
    GRID: 'grid',
    HAIR_CROSS: 'hair-cross',
    HAND: 'hand',
    HEART_OUTLINED: 'heart-outlined',
    HEART: 'heart',
    HELP_WITH_CIRCLE: 'help-with-circle',
    HELP: 'help',
    HOME: 'home',
    HOUR_GLASS: 'hour-glass',
    IMAGE_INVERTED: 'image-inverted',
    IMAGE: 'image',
    IMAGES: 'images',
    INBOX: 'inbox',
    INFINITY: 'infinity',
    INFO_WITH_CIRCLE: 'info-with-circle',
    INFO: 'info',
    INSTALL: 'install',
    KEY: 'key',
    KEYBOARD: 'keyboard',
    LAB_FLASK: 'lab-flask',
    LANDLINE: 'landline',
    LANGUAGE: 'language',
    LAPTOP: 'laptop',
    LAYERS: 'layers',
    LEAF: 'leaf',
    LEVEL_DOWN: 'level-down',
    LEVEL_UP: 'level-up',
    LIFEBUOY: 'lifebuoy',
    LIGHT_BULB: 'light-bulb',
    LIGHT_DOWN: 'light-down',
    LIGHT_UP: 'light-up',
    LINE_GRAPH: 'line-graph',
    LINK: 'link',
    LIST: 'list',
    LOCATION_PIN: 'location-pin',
    LOCATION: 'location',
    LOCK_OPEN: 'lock-open',
    LOCK: 'lock',
    LOG_OUT: 'log-out',
    LOGIN: 'login',
    LOOP: 'loop',
    MAGNET: 'magnet',
    MAGNIFYING_GLASS: 'magnifying-glass',
    MAIL: 'mail',
    MAN: 'man',
    MAP: 'map',
    MASK: 'mask',
    MEDAL: 'medal',
    MEGAPHONE: 'megaphone',
    MENU: 'menu',
    MERGE: 'merge',
    MESSAGE: 'message',
    MIC: 'mic',
    MINUS: 'minus',
    MOBILE: 'mobile',
    MODERN_MIC: 'modern-mic',
    MOON: 'moon',
    MOUSE_POINTER: 'mouse-pointer',
    MOUSE: 'mouse',
    MUSIC: 'music',
    NETWORK: 'network',
    NEW_MESSAGE: 'new-message',
    NEW: 'new',
    NEWS: 'news',
    NEWSLETTER: 'newsletter',
    NOTE: 'note',
    NOTIFICATION: 'notification',
    NOTIFICATIONS_OFF: 'notifications-off',
    OLD_MOBILE: 'old-mobile',
    OLD_PHONE: 'old-phone',
    OPEN_BOOK: 'open-book',
    PALETTE: 'palette',
    PAPER_PLANE: 'paper-plane',
    PENCIL: 'pencil',
    PHONE: 'phone',
    PIE_CHART: 'pie-chart',
    PIN: 'pin',
    PLUS: 'plus',
    POPUP: 'popup',
    POWER_PLUG: 'power-plug',
    PRICE_RIBBON: 'price-ribbon',
    PRICE_TAG: 'price-tag',
    PRINT: 'print',
    PROGRESS_EMPTY: 'progress-empty',
    PROGRESS_FULL: 'progress-full',
    PROGRESS_ONE: 'progress-one',
    PROGRESS_TWO: 'progress-two',
    PUBLISH: 'publish',
    QUOTE: 'quote',
    RADIO: 'radio',
    REMOVE_USER: 'remove-user',
    REPLY_ALL: 'reply-all',
    REPLY: 'reply',
    RESIZE_100: 'resize-100%',
    RESIZE_FULL_SCREEN: 'resize-full-screen',
    RETWEET: 'retweet',
    ROCKET: 'rocket',
    ROUND_BRUSH: 'round-brush',
    RSS: 'rss',
    RULER: 'ruler',
    SAVE: 'save',
    SCISSORS: 'scissors',
    SELECT_ARROWS: 'select-arrows',
    SHARE_ALTERNATIVE: 'share-alternative',
    SHARE: 'share',
    SHAREABLE: 'shareable',
    SHIELD: 'shield',
    SHOP: 'shop',
    SHOPPING_BAG: 'shopping-bag',
    SHOPPING_BASKET: 'shopping-basket',
    SHOPPING_CART: 'shopping-cart',
    SHUFFLE: 'shuffle',
    SIGNAL: 'signal',
    SOUND_MIX: 'sound-mix',
    SOUND_MUTE: 'sound-mute',
    SOUND: 'sound',
    SPORTS_CLUB: 'sports-club',
    SPREADSHEET: 'spreadsheet',
    SQUARED_CROSS: 'squared-cross',
    SQUARED_MINUS: 'squared-minus',
    SQUARED_PLUS: 'squared-plus',
    STAR_OUTLINED: 'star-outlined',
    STAR: 'star',
    STOPWATCH: 'stopwatch',
    SUITCASE: 'suitcase',
    SWAP: 'swap',
    SWEDEN: 'sweden',
    SWITCH: 'switch',
    TABLET_MOBILE_COMBO: 'tablet-mobile-combo',
    TABLET: 'tablet',
    TAG: 'tag',
    TEXT_DOCUMENT_INVERTED: 'text-document-inverted',
    TEXT_DOCUMENT: 'text-document',
    TEXT: 'text',
    THERMOMETER: 'thermometer',
    THUMBS_DOWN: 'thumbs-down',
    THUMBS_UP: 'thumbs-up',
    THUNDER_CLOUD: 'thunder-cloud',
    TICKET: 'ticket',
    TIME_SLOT: 'time-slot',
    TOOLS: 'tools',
    TRAFFIC_CONE: 'traffic-cone',
    TRASH: 'trash',
    TREE: 'tree',
    TRIANGLE_DOWN: 'triangle-down',
    TRIANGLE_LEFT: 'triangle-left',
    TRIANGLE_RIGHT: 'triangle-right',
    TRIANGLE_UP: 'triangle-up',
    TROPHY: 'trophy',
    TV: 'tv',
    TYPING: 'typing',
    UNINSTALL: 'uninstall',
    UNREAD: 'unread',
    UNTAG: 'untag',
    UPLOAD_TO_CLOUD: 'upload-to-cloud',
    UPLOAD: 'upload',
    USER: 'user',
    USERS: 'users',
    V_CARD: 'v-card',
    VIDEO_CAMERA: 'video-camera',
    VIDEO: 'video',
    VINYL: 'vinyl',
    VOICEMAIL: 'voicemail',
    WALLET: 'wallet',
    WARNING: 'warning',
    WATER: 'water',
    APP_STORE: 'app-store',
    BAIDU: 'baidu',
    GOOGLE_PLAY: 'google-play',
    HOUZZ: 'houzz',
    MAIL_WITH_CIRCLE: 'mail-with-circle',
    WINDOWS_STORE: 'windows-store',
};

Icon.Size = {
    HUGE: 'huge',
    BIG: 'big',
    SMALL: 'small',
    TINY: 'tiny',
};

/**
 * User: Oleg Kamlowski <oleg.kamlowski@thomann.de>
 * Date: 15.10.2019
 * Time: 18:12
 */
export default Icon;
